
int bitXor(int, int);
int test_bitXor(int, int);
int isTmax(int);
int test_isTmax(int);
int isLessOrEqual(int, int);
int test_isLessOrEqual(int, int);
int rempwr2(int, int);
int test_rempwr2(int, int);
int subOK(int, int);
int test_subOK(int, int);
int isAsciiDigit(int);
int test_isAsciiDigit(int);
int reverseBytes(int);
int test_reverseBytes(int);
int ezThreeFourths(int);
int test_ezThreeFourths(int);
int trueThreeFourths(int);
int test_trueThreeFourths(int);
int bitParity(int);
int test_bitParity(int);
int tc2sm(int);
int test_tc2sm(int);
int isPower2(int);
int test_isPower2(int);
unsigned float_neg(unsigned);
unsigned test_float_neg(unsigned);
unsigned float_i2f(int);
unsigned test_float_i2f(int);
